services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    container_name: web_storage_app_prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      - DB_HOST=${PROD_DB_HOST:-10.0.0.110}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${PROD_DB_DATABASE:-web_storage_prod}
      - DB_USERNAME=${PROD_DB_USERNAME:-admin_prod}
      - DB_PASSWORD=${PROD_DB_PASSWORD:-secret_prod}
    volumes:
      - prod_storage:/var/www/html/storage
    networks:
      - prod_net

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    container_name: web_storage_nginx_prod
    restart: unless-stopped
    ports:
      - "1234:1234"
    volumes:
      - /etc/letsencrypt/archive/server1.fabriciolr.online:/etc/nginx/cert:ro
    depends_on:
      - app
    networks:
      - prod_net

volumes:
  prod_storage:

networks:
  prod_net:
    driver: bridge
