FROM nginx:latest

COPY docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY public /var/www/html/public
COPY /etc/letsencrypt/archive/server1.fabriciolr.online /etc/nginx/cert

EXPOSE 1234

CMD ["nginx", "-g", "daemon off;"]